version: "3.8"
services:
  # ---------- API GATEWAY ----------
  api-gateway:
    image: redbasketapp/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"  # âœ… Expose container port to host
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/gateway-health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # ---------- Auth Serivce ----------
  auth-service:
    image: redbasketapp/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # ---------- Product Serivce ----------
  product-service:
    image: redbasketapp/product-service:latest
    container_name: product-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # ---------- Admin Serivce ----------
  admin-service:
    image: redbasketapp/admin-service:latest
    container_name: product-service
    restart: unless-stopped
    env_file:
    - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
  
  # ---------- Manager Serivce ----------
  manager-service:
    image: redbasketapp/manager-service:latest
    container_name: manager-serrvice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # ---------- USER UI ----------
  user-ui:
    image: redbasketapp/user-ui:latest
    container_name: user-ui
    env_file:
    - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=https://redbasketapp.hopto.org
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'

  # # ---------- VENDOR UI ----------
  # vendor-ui:
  #   build:
  #     context: .
  #     dockerfile: apps/vendor-ui/Dockerfile
  #   image: durvesh502/meato-vendor-ui:latest
  #   container_name: vendor-ui
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_SERVER_URL=https://redbasketapp.hopto.org
  #   restart: unless-stopped
  #   expose:
  #     - "3003"

  # # ---------- MANAGER UI ----------
  # manager-ui:
  #   build:
  #     context: .
  #     dockerfile: apps/manager-ui/Dockerfile
  #   image: durvesh502/meato-manager-ui:latest
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_SERVER_URL=https://redbasketapp.hopto.org
  #   container_name: manager-ui
  #   restart: unless-stopped
  #   expose:
  #     - "3002"

  # ---------- ADMIN UI ----------
  admin-ui:
    image: redbasketapp/admin-ui:latest
    container_name: admin-ui
    env_file:
    - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=https://redbasketapp.hopto.org
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'

  # # ---------- POSTGRESQL ----------
  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres-db
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     POSTGRES_DB: meato_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - meato_net

  # ---------- NGINX REVERSE PROXY ----------
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.config:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - api-gateway
      - user-ui
      # - vendor-ui
      # - manager-ui
      - admin-ui

    # EC2 CLI
    # docker-compose -f docker-compose.production.yaml up -d api-gateway